### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by QwertyUser451** [greysdawn/pluralkit-web#27]
When trying to update my PK System, it mentions that I have a "Network Error".

**Comment by greysdawn** [comment]
Ack, hit the wrong button

Sorry we didn't see this sooner! It looks like it's an issue with some image hosts and how we validate avatars. Gonna disable the validation for now and just make sure that a link is given

**Comment by greysdawn** [comment]
We changed the validation method so it should work better now :3  
Let us know if anything breaks again
